model = "gpt-5.6-sol"
model_reasoning_effort = "low"

default_permissions = "dev"
approval_policy = "on-request"

model_verbosity = "low"             # 输出极简
personality = "pragmatic"           # 务实风格
model_reasoning_summary = "concise" # 简短摘要

[tui]
status_line = [
  "model-with-reasoning",
  "current-dir",
  "permissions",
  "context-used",
  "weekly-limit",
  "total-input-tokens",
  "total-output-tokens",
]
status_line_use_colors = true

[features.network_proxy]
enabled = true

[features.multi_agent_v2]
enabled = true
max_concurrent_threads_per_session = 6
multi_agent_mode_hint_text = """
Use a subagent to execute the task when the intermediate execution 
steps of the task have no persistent value and only the final result matters.

If the context of the tasks may be the same, you should obtain the context first and then delegate.

Use the waiter agent to wait for long-running command（like install, ci, agent_cli etc.）.
"""

[agents]
max_depth = 1

# permissions

[permissions.dev]
description = "Normal local dev"
extends = ":workspace"

[permissions.dev.filesystem]
glob_scan_max_depth = 8

":minimal" = "read"

# MAC
"~/Library/pnpm" = "write"
"~/Library/Caches/pnpm" = "write"

# Linux
"~/.npm" = "write"
"~/.nvm/versions/node" = "read"

"~/.cache/uv" = "write"
"~/.cache/Cypress" = "write"
"~/.cache/puppeteer" = "write"
"~/.cache/ms-playwright" = "write"
"~/.local/share/pnpm/store" = "write"

"~/.local/share/opencode" = "write"


[permissions.dev.filesystem.":workspace_roots"]
"." = "write"
".git" = "write"
".git/**" = "write"
"*.pem" = "deny"
"**/*.pem" = "deny"

"*.key" = "deny"
"**/*.key" = "deny"

[permissions.dev.network]
enabled = true
allow_local_binding = true

[permissions.dev.network.domains]
"localhost" = "allow"
"127.0.0.1" = "allow"
"::1" = "allow"

[permissions.dev.network.unix_sockets]
"/var/run/docker.sock" = "allow"

# MCP
[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
bearer_token_env_var = "CONTEXT7_API_KEY"

[mcp_servers.playwright]
command = "pnpm"
args = ["dlx", "-y", "@playwright/mcp@latest"]
