set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 10
set -g focus-events on
set -s set-clipboard on
set -g allow-passthrough on

set -as terminal-features ',xterm-ghostty:clipboard'
set -as terminal-features ',tmux-256color:clipboard'
set -as terminal-features ',screen-256color:clipboard'

set -as terminal-overrides ',xterm-ghostty:Ms=\E]52;%p1%s;%p2%s\007'
set -as terminal-overrides ',tmux-256color:Ms=\E]52;%p1%s;%p2%s\007'
set -as terminal-overrides ',screen-256color:Ms=\E]52;%p1%s;%p2%s\007'

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind | split-window -h
bind - split-window -v

setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
